# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/MEHMET/Desktop/istanbul_live_mobese/istanbul_city_surveillance_cameras_Gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1342, 876)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("#page_menu{border-image: url(:/icons/icons/6264983.jpg);}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_menu = QtWidgets.QWidget()
        self.page_menu.setObjectName("page_menu")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_menu)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 0, 10, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.comboBox_2 = QtWidgets.QComboBox(self.page_menu)
        self.comboBox_2.setMinimumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.comboBox_2.setFont(font)
        self.comboBox_2.setMaxVisibleItems(10)
        self.comboBox_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.page_menu)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_menu)
        self.page_predict = QtWidgets.QWidget()
        self.page_predict.setObjectName("page_predict")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_predict)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_mobese = QtWidgets.QLabel(self.page_predict)
        self.label_mobese.setMinimumSize(QtCore.QSize(0, 730))
        self.label_mobese.setText("")
        self.label_mobese.setObjectName("label_mobese")
        self.verticalLayout_2.addWidget(self.label_mobese)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_predict)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.label = QtWidgets.QLabel(self.page_predict)
        self.label.setMinimumSize(QtCore.QSize(1000, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 0, 255);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_predict)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1342, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Select region..."))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Mecidiyeköy"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "FSM Köprüsü"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "268-s yolu asiyan"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Beşiktaş"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "Sirkeci"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "Acıbadem Köprüsü"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "Kadıköy Rıhtım"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "Kağıthane"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "Çavuşbaşı"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "Dünya gazetesi"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "Atatürk Havalimanı"))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "15 temmuz şehitler köprüsü"))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "Bahçe Taksim"))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "Eyüp Feshane"))
        self.comboBox_2.setItemText(15, _translate("MainWindow", "Harem ido"))
        self.comboBox_2.setItemText(16, _translate("MainWindow", "H.U Tuneli beykoz"))
        self.comboBox_2.setItemText(17, _translate("MainWindow", "Eminönü"))
        self.comboBox_2.setItemText(18, _translate("MainWindow", "Eyüp Sultan"))
        self.comboBox_2.setItemText(19, _translate("MainWindow", "İstiklal Caddesi 1"))
        self.comboBox_2.setItemText(20, _translate("MainWindow", "İstiklal Caddesi 2"))
        self.comboBox_2.setItemText(21, _translate("MainWindow", "Mısır Çarşısı"))
        self.comboBox_2.setItemText(22, _translate("MainWindow", "Miniatürk"))
        self.comboBox_2.setItemText(23, _translate("MainWindow", "Saraçhane"))
        self.comboBox_2.setItemText(24, _translate("MainWindow", "Sultan Ahmet"))
        self.comboBox_2.setItemText(25, _translate("MainWindow", "Bağdat caddesi"))
        self.pushButton.setText(_translate("MainWindow", "Connect and Predict"))
        self.pushButton_2.setText(_translate("MainWindow", "<< Back to menu page"))

import icons_rc
